

import { MotivationalQuote } from "./types";

export const ARABIC_STRINGS = {
  APP_TITLE: "منظم المراجعات الدراسية",
  ADD_SUBJECT: "إضافة مادة دراسية جديدة",
  EDIT_SUBJECT: "تعديل المادة الدراسية",
  SUBJECT_NAME_PLACEHOLDER: "اسم المادة (مثال: فيزياء)",
  ADD_LECTURE: "إضافة محاضرة/وحدة جديدة",
  EDIT_LECTURE: "تعديل المحاضرة/الوحدة",
  LECTURE_NAME_PLACEHOLDER: "اسم المحاضرة (مثال: الفصل الأول)",
  FIRST_STUDY_DATE: "تاريخ أول مذاكرة",
  SAVE: "حفظ",
  CANCEL: "إلغاء",
  EDIT: "تعديل",
  DELETE: "حذف",
  SUBJECTS: "المواد الدراسية",
  LECTURES: "المحاضرات والوحدات",
  NO_SUBJECTS_PROMPT: "لا توجد مواد دراسية حتى الآن. ابدأ بإضافة مادة جديدة!",
  NO_LECTURES_PROMPT: "لا توجد محاضرات لهذه المادة. قم بإضافة محاضرة جديدة.",
  TASKS_TABLE: "جدول المهام", 
  NO_REVIEWS_SCHEDULED: "لا توجد مراجعات مجدولة حاليًا. قم بإضافة محاضرات وحدد تاريخ أول مذاكرة لها.",
  NO_TASKS_TODAY: "لا توجد مهام مجدولة لليوم.",
  NO_TASKS_THIS_WEEK: "لا توجد مهام مجدولة لهذا الأسبوع.",
  NO_TASKS_THIS_MONTH: "لا توجد مهام مجدولة لهذا الشهر.",
  VIEW_DAILY: "يومي",
  VIEW_WEEKLY: "أسبوعي",
  VIEW_MONTHLY: "شهري",
  COMPLETE_REVIEW: "إكمال المراجعة",
  MARK_AS_COMPLETE: "تمت المراجعة بنجاح",
  EDIT_REVIEW_DATE: "تعديل تاريخ المراجعة",
  TARGET_DATE: "التاريخ المستهدف",
  SUBJECT_NAME: "المادة",
  LECTURE_NAME: "المحاضرة/الوحدة",
  ACTIONS: "إجراءات",
  CONFIRM_DELETE_TITLE: "تأكيد الحذف",
  CONFIRM_DELETE_SUBJECT_MSG: (subjectName: string) => `هل أنت متأكد أنك تريد حذف المادة "${subjectName}" وجميع محاضراتها ومراجعاتها المرتبطة بها؟ لا يمكن التراجع عن هذا الإجراء.`,
  CONFIRM_DELETE_LECTURE_MSG: (lectureName: string) => `هل أنت متأكد أنك تريد حذف المحاضرة "${lectureName}" وجميع مراجعاتها المجدولة؟`,
  YES: "نعم، حذف", // Also used for "Yes, Import"
  NO: "لا، إلغاء",
  STATISTICS: "الإحصائيات",
  REVIEWS_COMPLETED_COUNT: "المراجعات المكتملة",
  REVIEWS_PENDING_COUNT: "المراجعات المتبقية",
  REVIEWS_OVERDUE_COUNT: "المراجعات المتأخرة",
  TOTAL_LECTURES_WITH_REVIEWS: "إجمالي المحاضرات ذات المراجعات النشطة",
  EXPORT_CALENDAR: "تصدير إلى التقويم (.ics)",
  EXPORT_ALL_REVIEWS: "تصدير كل المراجعات القادمة",
  EXPORT_SUBJECT_REVIEWS_OPTION: "تصدير مراجعات مادة محددة...",
  SELECT_SUBJECT_TO_EXPORT: "اختر مادة لتصدير مراجعاتها:",
  ALL_SUBJECTS: "كل المواد",
  EXPORT_SUCCESS: "تم تصدير ملف التقويم بنجاح!",
  EXPORT_NO_REVIEWS: "لا توجد مراجعات لتصديرها.",
  PLEASE_FILL_ALL_FIELDS: "يرجى ملء جميع الحقول المطلوبة.",
  DATE_INVALID: "تاريخ أول مذاكرة غير صالح.",
  STUDY_PLANNER: "مخطط الدراسة الذكي", // Can be used as a subtitle or description
  MANAGE_SUBJECTS_LECTURES: "إدارة المواد الدراسية والمحاضرات",
  OVERDUE: "متأخرة",
  FOR: "لِ",
  CALENDAR_VIEW_TITLE: "تقويم المراجعات الشهري",
  REVIEWS_FOR_DATE: "المراجعات ليوم",
  NO_REVIEWS_FOR_DATE: "لا توجد مراجعات مجدولة لهذا اليوم.",
  PREVIOUS_MONTH: "الشهر السابق",
  NEXT_MONTH: "الشهر التالي",
  WELCOME_TITLE: "أهلاً بك في منظم المراجعات الدراسية!",
  WELCOME_BUTTON: "ابدأ رحلتك الدراسية",
  THEME_LIGHT: "فاتح",
  THEME_DARK: "داكن",
  THEME_SYSTEM: "النظام",
  CURRENT_STREAK: "سلسلة الإنجاز الحالية",
  LONGEST_STREAK: "أطول سلسلة إنجاز",
  DAYS_UNIT: "أيام",
  DAY_UNIT: "يوم",
  PROGRESS: "التقدم",
  REVIEWS_COMPLETED_OF_TOTAL: (completed: number, total: number) => `${completed} / ${total} مراجعات مكتملة`,
  LECTURE_REVIEW_SCHEDULE_TITLE: "جدول مراجعات المحاضرة:",
  REVIEW_STATUS_COMPLETED: "مكتملة",
  REVIEW_STATUS_NEXT_UPCOMING: "المراجعة التالية",
  REVIEW_STATUS_FUTURE_POTENTIAL: "مراجعة مستقبلية",
  REVIEW_STATUS_FULLY_COMPLETED: "جميع المراجعات مكتملة لهذه المحاضرة.",
  REVIEW_CYCLE_LABEL: (cycle: number) => `المراجعة ${cycle}`,
  FUTURE_REVIEW_NOTICE_TOAST: "سيتاح إكمال هذه المراجعة في تاريخها المحدد.",
  FUTURE_REVIEW_NOTICE_TOOLTIP: "لا يمكن إكمال المراجعة قبل تاريخها المحدد.",
  INVALID_REVIEW_DATE_TOAST: "تاريخ المراجعة غير صالح. يرجى تعديله.",
  INVALID_REVIEW_DATE_TOOLTIP: "تاريخ المراجعة المحدد غير صالح.",
  SEARCH_PLACEHOLDER: "ابحث عن مادة...", 
  NO_SEARCH_RESULTS: "لم يتم العثور على نتائج تطابق بحثك.",
  CLEAR_SEARCH: "مسح البحث",
  SETTINGS_TITLE: "الإعدادات",
  CUSTOM_REVIEW_INTERVALS_LABEL: "فترات المراجعة المخصصة (أيام)",
  CUSTOM_REVIEW_INTERVALS_PLACEHOLDER: "مثال: 1, 3, 7, 14, 30 (اتركه فارغًا للافتراضي)",
  CUSTOM_REVIEW_INTERVALS_HELP: (defaults: string) => `أدخل الأيام مفصولة بفواصل. الفترات الافتراضية: ${defaults}.`,
  SAVE_SETTINGS: "حفظ الإعدادات",
  SETTINGS_SAVED_SUCCESS: "تم حفظ الإعدادات بنجاح!",
  INVALID_INTERVALS_ERROR: "فترات المراجعة غير صالحة. يرجى إدخال أرقام موجبة مفصولة بفواصل.",
  LECTURE_NOTES_LABEL: "ملاحظات على المحاضرة (اختياري):",
  DISPLAY_LECTURE_NOTES_TITLE: "ملاحظات المحاضرة:",
  DAILY_FOCUS_TITLE: "تركيز اليوم",
  CRITICALLY_OVERDUE_REVIEWS: "متأخرة جداً",
  DUE_TODAY_REVIEWS: "مستحقة اليوم",
  BACK_TO_SUBJECTS: "العودة إلى قائمة المواد",
  SUBJECT_PAGE_TITLE: (subjectName: string) => `تفاصيل مادة: ${subjectName}`,
  MANAGE_LECTURES_FOR_SUBJECT: "إدارة محاضرات المادة:",
  NO_LECTURES_IN_SUBJECT_PROMPT: "لا توجد محاضرات لهذه المادة حتى الآن. ابدأ بإضافة محاضرة جديدة!",
  RESET_TO_DEFAULT_SETTINGS: "العودة للإعدادات الافتراضية",
  DEFAULT_SETTINGS_RESTORED: "تمت استعادة فترات المراجعة الافتراضية بنجاح!",
  // Sidebar specific
  MAIN_MENU: "القائمة الرئيسية",
  DASHBOARD_TITLE: "لوحة التحكم",
  SUBJECTS_SECTION_TITLE: "المواد الدراسية", // For sidebar link if needed, or reuse SUBJECTS
  SCHEDULED_TASKS_LINK: "المهام المجدولة",
  CALENDAR_LINK: "التقويم",
  STATISTICS_LINK: "الإحصائيات",
  OPEN_MENU: "فتح القائمة",
  CLOSE_MENU: "إغلاق القائمة",
  THEME_SETTINGS_LABEL: "إعدادات المظهر",

  // Daily Tasks Feature
  DAILY_TASKS_PAGE_TITLE: "المهام اليومية",
  ADD_CUSTOM_TASK: "إضافة مهمة جديدة",
  ADD_CUSTOM_TASK_PLACEHOLDER: "اكتب نص المهمة هنا...",
  ADD_TASK_BUTTON: "إضافة مهمة",
  TODAYS_REVIEWS_SECTION_TITLE: "مراجعات اليوم",
  MY_TASKS_FOR_TODAY_SECTION_TITLE: "مهامي لليوم",
  NO_CUSTOM_TASKS_TODAY: "لا توجد مهام مخصصة أضفتها لليوم. ",
  NO_REVIEWS_DUE_TODAY: "لا توجد مراجعات مستحقة اليوم. رائع!",
  ALL_TASKS_COMPLETED_FOR_TODAY: "رائع! لقد أكملت جميع مهامك ومراجعاتك لليوم.",
  TASK_ADDED_SUCCESS: "تمت إضافة المهمة بنجاح!",
  TASK_COMPLETED_SUCCESS: "تم إكمال المهمة بنجاح!",
  TASK_DELETED_SUCCESS: "تم حذف المهمة بنجاح!",
  CONFIRM_DELETE_TASK_MSG: (taskText: string) => `هل أنت متأكد أنك تريد حذف المهمة: "${taskText}"؟`,
  TASKS_FOR_DATE: "المهام ليوم",
  NO_TASKS_FOR_SELECTED_DATE: "لا توجد مهام أو مراجعات مجدولة لهذا اليوم.",

  // Data Export/Import
  DATA_MANAGEMENT_TITLE: "إدارة البيانات (النسخ الاحتياطي والاستعادة)",
  EXPORT_DATA: "تصدير البيانات",
  IMPORT_DATA: "استيراد البيانات",
  EXPORT_DATA_SUCCESS: "تم تصدير ملف بياناتك بنجاح!",
  IMPORT_DATA_SUCCESS: "تم استيراد البيانات وتطبيقها بنجاح!",
  IMPORT_DATA_ERROR_GENERAL: "حدث خطأ أثناء محاولة استيراد البيانات. يرجى التأكد من أن الملف صحيح.",
  IMPORT_DATA_INVALID_FILE: "ملف الاستيراد غير صالح أو لا يحتوي على البيانات المتوقعة. لم يتم إجراء أي تغييرات.",
  SELECT_FILE_TO_IMPORT: "اختر ملف بيانات (.json) للاستيراد",
  CONFIRM_IMPORT_TITLE: "تأكيد استيراد البيانات",
  CONFIRM_IMPORT_OVERWRITE_MSG: "سيؤدي استيراد البيانات الجديدة إلى الكتابة فوق جميع بياناتك الحالية في التطبيق. لا يمكن التراجع عن هذا الإجراء. هل أنت متأكد أنك تريد المتابعة؟",
  YES_IMPORT: "نعم، استيراد والكتابة فوق",
};

export const MOTIVATIONAL_QUOTES: MotivationalQuote[] = [
  { id: "q1", text: "النجاح ليس مفتاح السعادة، السعادة هي مفتاح النجاح. إذا أحببت ما تفعله، فستنجح." },
  { id: "q2", text: "لا تنتظر الفرصة، اصنعها بنفسك." },
  { id: "q3", text: "التعليم هو أقوى سلاح يمكنك استخدامه لتغيير العالم." },
  { id: "q4", text: "ابدأ من حيث أنت. استخدم ما لديك. افعل ما تستطيع." },
  { id: "q5", text: "الطريق إلى النجاح دائمًا قيد الإنشاء." },
  { id: "q6", text: "كل إنجاز عظيم كان يعتبر ذات يوم مستحيلاً." },
  { id: "q7", text: "العلم نور، والجهل ظلام. استثمر في نورك." },
  { id: "q8", text: "لا تخف من التقدم ببطء، خف فقط من الوقوف ساكناً." },
  { id: "q9", text: "المستقبل ملك لأولئك الذين يؤمنون بجمال أحلامهم." },
  { id: "q10", text: "القراءة للعقل كالرياضة للجسم." }
];

// Default review intervals in days after the *previous* review event (or first study date)
export const DEFAULT_REVIEW_INTERVALS_DAYS = [1, 3, 7, 14, 30]; 
export const LOCAL_STORAGE_KEY = 'studyAppSpacedRepetitionData';
export const THEME_STORAGE_KEY = 'studyAppSpacedRepetitionData-theme'; // Separate key for theme for immediate loading

export const generateReviewCycleLabels = (intervalsCount: number) => {
  const labels = [];
  for (let i = 0; i < intervalsCount; i++) {
    labels.push(ARABIC_STRINGS.REVIEW_CYCLE_LABEL(i + 1));
  }
  return labels;
};

export const EXPORT_APP_DATA_FILENAME_PREFIX = 'منظم-المراجعات-بيانات-النسخ-الاحتياطي-'; // Date will be appended